sudo: false
language: node_js
dist: trusty
node_js:
  - "node"
install: npm install
script:
  - gulp
cache:
  directories:
    - node_modules

#deploy:
#  provider: s3
#  access_key_id: "YOUR AWS ACCESS KEY"
#  secret_access_key: "YOUR AWS SECRET KEY"
#  bucket: "S3 Bucket"